export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL';

export const GET_BUSINESS_APPOINTMENT_REQUEST =
  'GET_BUSINESS_APPOINTMENT_REQUEST';
export const GET_BUSINESS_APPOINTMENT_SUCCESS =
  'GET_BUSINESS_APPOINTMENT_SUCCESS';
export const GET_BUSINESS_APPOINTMENT_FAIL = 'GET_BUSINESS_APPOINTMENT_FAIL';

export const GET_USER_APPOINTMENT_REQUEST = 'GET_USER_APPOINTMENT_REQUEST';
export const GET_USER_APPOINTMENT_SUCCESS = 'GET_USER_APPOINTMENT_SUCCESS';
export const GET_USER_APPOINTMENT_FAIL = 'GET_USER_APPOINTMENT_FAIL';
