export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL';

export const GET_BUSINESS_APPOINTMENT_REQUEST =
  'GET_BUSINESS_APPOINTMENT_REQUEST';
export const GET_BUSINESS_APPOINTMENT_SUCCESS =
  'GET_BUSINESS_APPOINTMENT_SUCCESS';
export const GET_BUSINESS_APPOINTMENT_FAIL = 'GET_BUSINESS_APPOINTMENT_FAIL';

export const GET_USER_APPOINTMENT_REQUEST = 'GET_USER_APPOINTMENT_REQUEST';
export const GET_USER_APPOINTMENT_SUCCESS = 'GET_USER_APPOINTMENT_SUCCESS';
export const GET_USER_APPOINTMENT_FAIL = 'GET_USER_APPOINTMENT_FAIL';
export const GET_USER_APPOINTMENT_RESET = 'GET_USER_APPOINTMENT_RESET';

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL';

export const DASHBOARD_APPOINTMENT_REQUEST = 'DASHBOARD_APPOINTMENT_REQUEST';
export const DASHBOARD_APPOINTMENT_SUCCESS = 'DASHBOARD_APPOINTMENT_SUCCESS';
export const DASHBOARD_APPOINTMENT_FAIL = 'DASHBOARD_APPOINTMENT_FAIL';
