export const GET_ALL_BUSINESS_REQUEST = 'GET_ALL_BUSINESS_REQUEST';
export const GET_ALL_BUSINESS_SUCCESS = 'GET_ALL_BUSINESS_SUCCESS';
export const GET_ALL_BUSINESS_FAIL = 'GET_ALL_BUSINESS_FAIL';

export const GET_SINGLE_BUSINESS_REQUEST = 'GET_SINGLE_BUSINESS_REQUEST';
export const GET_SINGLE_BUSINESS_SUCCESS = 'GET_SINGLE_BUSINESS_SUCCESS';
export const GET_SINGLE_BUSINESS_FAIL = 'GET_SINGLE_BUSINESS_FAIL';

export const GET_USER_BUSINESS_REQUEST = 'GET_USER_BUSINESS_REQUEST';
export const GET_USER_BUSINESS_SUCCESS = 'GET_USER_BUSINESS_SUCCESS';
export const GET_USER_BUSINESS_FAIL = 'GET_USER_BUSINESS_FAIL';

export const CREATE_BUSINESS_REQUEST = 'CREATE_BUSINESS_REQUEST';
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const CREATE_BUSINESS_FAIL = 'CREATE_BUSINESS_FAIL';

export const EDIT_BUSINESS_REQUEST = 'EDIT_BUSINESS_REQUEST';
export const EDIT_BUSINESS_SUCCESS = 'EDIT_BUSINESS_SUCCESS';
export const EDIT_BUSINESS_FAIL = 'EDIT_BUSINESS_FAIL';
