export const GET_ALL_BUSINESS_REQUEST = 'GET_ALL_BUSINESS_REQUEST';
export const GET_ALL_BUSINESS_SUCCESS = 'GET_ALL_BUSINESS_SUCCESS';
export const GET_ALL_BUSINESS_FAIL = 'GET_ALL_BUSINESS_FAIL';

export const GET_SINGLE_BUSINESS_REQUEST = 'GET_SINGLE_BUSINESS_REQUEST';
export const GET_SINGLE_BUSINESS_SUCCESS = 'GET_SINGLE_BUSINESS_SUCCESS';
export const GET_SINGLE_BUSINESS_FAIL = 'GET_SINGLE_BUSINESS_FAIL';

export const CREATE_BUSINESS_REQUEST = 'CREATE_BUSINESS_REQUEST';
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const CREATE_BUSINESS_FAIL = 'CREATE_BUSINESS_FAIL';
